export {
  ALLERGY_SEVERITIES,
  GENDERS,
  PRIORITIES,
  RESOURCE_STATUSES,
  RESOURCE_TYPES,
  SERVICE_KINDS,
  SIMULATION_EVENT_TYPES,
  STAGES,
  TEST_RESULT_FLAGS,
} from "./domain";
export type {
  Allergy,
  AllergySeverity,
  BottleneckAlert,
  Diagnosis,
  Gender,
  Medication,
  Metrics,
  MetricsBlock,
  Patient,
  PatientHistory,
  Priority,
  Recommendation,
  RequiredService,
  Resource,
  ResourceStatus,
  ResourceType,
  ServiceKind,
  SimulationEventType,
  SimState,
  Stage,
  TestResult,
  TestResultFlag,
  TimelineEvent,
  Treatment,
} from "./domain";
export type {
  ApiError,
  ApiErrorDetail,
  ApiSuccess,
  DoctorBriefResult,
  HealthStatus,
  OperationsSnapshot,
  SimulationStatus,
  SimulationResetResult,
  SimulationTickEvent,
  SimulationTickResult,
} from "./contracts";
